### ISSUE TITLE
Only one Tilt works at a time

### ISSUE THREAD

**Issue by DrMandible** [mkosir/react-parallax-tilt#1]
### 🐛 Issue/Bug Report Template

**Describe the bug**  
Multiple Tilts won't work at the same time. Only the most recently instanced will work.

**To Reproduce**  
See my CSB here: https://codesandbox.io/s/parallax-tests-h584m

**Expected behavior**
Both elements on the screen are configured identically other than image and text. They should behave the same.

- Browser:
- Version: "react-parallax-tilt":
- ...

**Comment by mkosir** [comment]
Bug fix is merged and deployed in the newest version `1.3.20`.  
Please check and confirm if it's working for you as expected?

**Comment by DrMandible** [comment]
@mkosir Works great! My first bug report and it was successful, yay! Was kinda scared you'd tell me I was using it wrong. Thanks!!
