### ISSUE TITLE
Custom transitionSpeed value cancelled after certain time or mousevents

### ISSUE THREAD

**Issue by nwesthoff** [mkosir/react-parallax-tilt#13]
### 🐛 Custom transitionSpeed value cancelled after certain time or mousevents

**Describe the bug**  
My custom set transition speed value is cancelled/bypassed after certain time or maybe (?) mousevents. It very noticeably switches from being smoothed to instantly responding. Upon moving the cursor outside and then inside the element the issue is (temporarily) resolved.

**To Reproduce**  

1. Create a `<Tilt />` component
2. Set a custom `transitionSpeed` prop
3. Wiggle your mouse around for a few seconds (while staying within the frame)
4. The transition speed is now instant
5. Move the cursor outside the component, then back in
6. Works again, but then issue repeats when you stay inside again

![](https://media.giphy.com/media/ltxOwEkR8jdclslPup/giphy.gif)

**Expected behavior**  
I expect the transition speed to stay slow for as long as the prop is not unset

**Link to demo (highly encouraged)**  
[CodeSandbox](https://codesandbox.io/s/tilt-parallax-image-react-parallax-tilt-forked-ein58) demo.

**Code snippets**  
If applicable, add code samples to help explain your problem.

**Environment**

- Browser: Chrome 85.0.4183.121 on Windows 10
- Version: "react-parallax-tilt": tested 1.0.13 and (currently latest) 1.4.65

**Additional context**  
I expect it has to do with specifically higher values for transition speed, but it might also be an effect of the change being more noticeable.

**Comment by mkosir** [comment]
Hi @nwesthoff, thanks for providing detailed bug report with reproducible demo link!
Bug fix is merged and deployed in the newest version `1.4.75`, please check and confirm if it's working for you as expected?

**Comment by nwesthoff** [comment]
Hey @mkosir, looks good on my end! Thanks
