### ISSUE TITLE
Component dropping effects after animating in

### ISSUE THREAD

**Issue by senwmn** [mkosir/react-parallax-tilt#18]
### 🐛 Component dropping effects after animating in

After animating a Tilt component in based on X or Y values, the X and Y axis for the tilt component seems to be locked and reversed in a way. 

I've made a test sandbox here: 
[https://codesandbox.io/s/tender-pasteur-f9lmc](https://codesandbox.io/s/tender-pasteur-f9lmc)

**Expected behavior**  
There's 3 tilt components labelled. The middle component labelled 'without motion' should be the effect for the 'with motion', but theres some strange behaviour going on. There's no issue when you add the event to the whole window though, so it is most likely something to do with the animating I believe. All the components have the same props and everything too.  

**Environment**

- Browser: Chrome / Mac
- Version: "react-parallax-tilt": 1.4.70

❤️ **this package btw!**
TIA

**Comment by sher-s7** [comment]
I've been having the same issue. Whenever the Tilt component is moved in any way, it's animation gets offset and moves in a weird way.

**Comment by sher-s7** [comment]
@mkosir Thanks! It's working, but there are two other problems now:

1. On page load the tilt components have a glare on them until you hover over them
2. When the tilt components move the animation isn't offset anymore (thank you), but the components do have a slight tilt

Here's a video of those two problems


https://user-images.githubusercontent.com/37381007/106939273-0c53cc00-66ee-11eb-8bd4-92f962dfe86c.mp4

**Comment by mkosir** [comment]
@sher-s7 thank you for the video, it clearly show the issue you are having, but I'm unable to reproduce it. Could you please create and share a demo link?

**Comment by sher-s7** [comment]
@mkosir This is slightly similar https://codesandbox.io/s/gifted-river-vjhhj?file=/src/App.js
After pushing the tilt components down you can see they get rotated, but work fine after hovering over them

**Comment by mkosir** [comment]
@sher-s7 Big thanks for provided demo 👍 , I was able to pinpoint the issue.
Please check if the latest release `1.4.78` is working for you as expected?

**Comment by sher-s7** [comment]
@mkosir Wow, that's perfect. Thank you very much for the fix 👌
