### ISSUE TITLE
Cannot read property 'style' of null

### ISSUE THREAD

**Issue by WaqqarSuleman** [mkosir/react-parallax-tilt#26]
Hi, 

I keep getting this error when my app hot reloads after a change. 
Here is my code:

```
const { loading, error, data } = useFetch(getBannersAPI, fetchId);
let content;
	if (loading) {
		content = <Loading />;
	} else if (error) {
		content = <Error>{error.message}</Error>;
	} else if (data?.data?.rows?.length > 0) {
		content = (
			<div className='banner-container'>
				{data?.data?.rows.map(({ id, name, image_url }) => (
					<Card key={id} className='bg-dark'>
						<Tilt scale={0.97}>
							<Card.Img variant='top' src={image_url} />
						</Tilt>
						<Card.Body className='pb-0 text-light'>
							<Card.Title className='d-flex justify-content-between'>
								<strong>{name}</strong>
								<section>
									<IconButton
										title='Edit Banner'
										onClick={() => toggleSaveBannerModal({ id, name, image_url })}
									>
										<InlineIcon icon={bxsEditAlt} color='cornflowerblue' />
									</IconButton>

									<IconButton title='Delete Banner' onClick={() => deleteBannerHandler(id)}>
										<InlineIcon icon={delete24Filled} color='firebrick' />
									</IconButton>
								</section>
							</Card.Title>
						</Card.Body>
					</Card>
				))}
			</div>
		);
	} else {
		content = <NoData>No Banner Found!</NoData>;
	}

```
How to fix this issue?

**Comment by mkosir** [comment]
Hi @WaqqarSuleman, please follow the [issue template](https://github.com/mkosir/react-parallax-tilt/blob/master/.github/ISSUE_TEMPLATE.md) (library version, demo link etc.)

**Comment by nwesthoff** [comment]
Hey @mkosir, I'm having the same issue (with Next.js), so I've taken the liberty to jump in on this issue. I'm not 100% sure whether this is an SSR issue, but I wasn't able to reproduce with plain React and `setInterval()` to conditionally load it.

### 🐛 Issue/Bug Report Template

**Describe the bug**
Getting console error:
```
Uncaught TypeError: Cannot read property 'style' of null
    at i.resetWrapperElTransform (react-parallax-tilt.es5.js?6058:1)
    at e.renderFrame (react-parallax-tilt.es5.js?6058:1)
```

**To Reproduce**  
Steps to reproduce the behavior:

1. Conditionally use Tilt component
2. Disable it client-side (like in `useEffect`)
3. Refresh page

**Expected behavior**  
Not throw an error when using react-parallax-tilt dynamically (in a server side rendered environment)

**Link to demo (required)**  
[CodeSandbox](https://codesandbox.io/s/peaceful-pond-ep4dg?file=/pages/index.js)

**Code snippets**  
Conditionally rendering as such. Loaded is triggered in `useEffect`.
```jsx
{loaded ? (
        <Tilt>
          <div>
            <h1>React Parallax Tilt</h1>
          </div>
        </Tilt>
      ) : null}
      ```

**Environment**
- OS: MacOS Big Sur
- Browser: Chrome 88.0.4324.182
- Version: "react-parallax-tilt": 1.4.89 (latest)

Hope this helps @WaqqarSuleman as well :)

**Comment by WaqqarSuleman** [comment]
> Hey @mkosir, I'm having the same issue (with Next.js), so I've taken the liberty to jump in on this issue. I'm not 100% sure whether this is an SSR issue, but I wasn't able to reproduce with plain React and `setInterval()` to conditionally unload it.
> 
> ### 🐛 Issue/Bug Report Template
> 
> **Describe the bug**
> Getting console error:
> ```
> Uncaught TypeError: Cannot read property 'style' of null
>     at i.resetWrapperElTransform (react-parallax-tilt.es5.js?6058:1)
>     at e.renderFrame (react-parallax-tilt.es5.js?6058:1)
> ```
> 
> **To Reproduce**  
> Steps to reproduce the behavior:
> 
> 1. Conditionally use Tilt component
> 2. Unload `<Tilt>` components it client-side (like in `useEffect`)
> 3. Refresh page
> 
> **Expected behavior**  
> Not throw an error when using react-parallax-tilt dynamically (in a server side rendered environment)
> 
> **Link to demo (required)**  
> [CodeSandbox](https://codesandbox.io/s/peaceful-pond-ep4dg?file=/pages/index.js)
> 
> **Code snippets**  
> Conditionally rendering as such. Loaded is triggered in `useEffect`.
> ```jsx
> {loaded ? null : (
>         <Tilt>
>           <div>
>             <h1>React Parallax Tilt</h1>
>           </div>
>         </Tilt>
>       )}
> ```
> 
> **Environment**
> - OS: MacOS Big Sur
> - Browser: Chrome 88.0.4324.182
> - Version: "react-parallax-tilt": 1.4.89 (latest)
> 
> Hope this helps @WaqqarSuleman as well :)

Thanks a lot for demonstrating this issue. I am using the library with plain React(so no SSR). Still facing the aforementioned issue. Hope it gets resolved soon.

**Comment by mkosir** [comment]
Hi @nwesthoff, thanks for providing detailed bug report with reproducible demo link!
This issue is a little harder to pinpoint but for a start I reverted some changes that were made for reducing npm package size, can you try out the newest version `1.4.90`?

**Comment by nwesthoff** [comment]
Seems like that does resolve it for me :)

[Forked Sandbox](https://codesandbox.io/s/intelligent-johnson-twvfe?file=/pages/index.js)

**Comment by mkosir** [comment]
Great, thx @nwesthoff 
@WaqqarSuleman can you check if the latest release `1.4.90` is also working for you as expected?

**Comment by WaqqarSuleman** [comment]
> Great, thx @nwesthoff
> @WaqqarSuleman can you check if the latest release `1.4.90` is also working for you as expected?

@mkosir The latest version is working as expected. Thanks!
