### ISSUE TITLE
If the functional component re-render it takes random position

### ISSUE THREAD

**Issue by manojf22** [mkosir/react-parallax-tilt#4]
### 🐛 Random transform rotate position on re-render

I used my tilt component on a child component, when I change any state value from the parent component then my tilt move some random position.

By default the style value of the tilt element is `transform: perspective(1000px) rotateX(0deg) rotateY(0deg) scale3d(1, 1, 1)`

but once the component re-render then the tilt element's style value is `transform: perspective(1000px) rotateX(-20deg) rotateY(20deg) scale3d(1, 1, 1)` by default

**App.js** (Parent component)
```
import React from 'react';
import SideMenu from "./Components/SideMenu";

function App() {
  const [test, setTest] = React.useState(0);
  setTimeout(()=>{
     setTest(test + 1);
  }, 2000);
  return (
    <>
      <SideMenu />
    </>
  );
}
export default App;
```
**SideMenu.js** (Child component)
```
import React from "react";
import Tilt from 'react-parallax-tilt';
import "./SideMenu.scss";

function SideMenu() {

  const [tilt, setTilt] = React.useState({
    className: 'menu',
    glareEnable: true,
    scale: 1.05,
    glareMaxOpacity: 0.05,
    glareColor: 'white',
    glarePosition: 'all'
  });

  return <aside>
    <nav>
      <Tilt {...tilt} >
        <a href="/" className="link">
          <i className="mdi mdi-spider-web" />
          <span>Dashboard</span>
        </a>
      </Tilt>
    </nav>
  </aside>
}

export default SideMenu;
```
**SCSS code**
```
nav {
    display: flex;
    flex-wrap: wrap;
    .menu{
      position: relative;
      width: 50%;
      height: 120px;
      border-radius: 6px 6px 0 0;
      transform-style: preserve-3d;
      i {
        transform: translateZ(20px);
        display: block;
        font-size: 36px;
      }
      span{
        transform: translateZ(30px);
        font-weight: 100;
      }
      .link {
        width: 100%;
        height: 120px;
        color: #ffffff;
        text-decoration: none;
        text-align: center;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        position: relative;
        z-index: 1;
      }
    }
```

**Comment by mkosir** [comment]
Hi @manojf22, thank you for concise bug description, but I'm having some troubles replicate it, would it be possible to create your example in some online code editor (such as [CodeSandbox](https://codesandbox.io/))?

**Comment by mkosir** [comment]
Closing this issue since inactivity, feel free to reopen it!

**Comment by bluefire2121** [comment]
This issue is also happening with me. On any render, the tilt starts out as:

`perspective(1000px) rotateX(20deg) rotateY(-20deg) scale3d(1, 1, 1)`

The above will even override the initial x and y values set as props.

**Comment by bluefire2121** [comment]
It seems to get stuck at the max tilt angles. 

```
tiltMaxAngleY
tiltMaxAngleX
```

**Comment by bluefire2121** [comment]
To solve this, I had to use make the tiltMax values a controlled component with initial values 0. I then had to set the values to the default 20 using the onEnter method.

```
const [tiltMax, setTiltMax] = useState({ x: 0, y: 0 });
<Tilt>
onEnter={() => setTiltMax({ x: 20, y: 20 });
</Tilt>
```

and this library should probably credit [vanilla-tilt](https://micku7zu.github.io/vanilla-tilt.js/index.html) and [tilt.js](https://gijsroge.github.io/tilt.js/).
