### ISSUE TITLE
Missing type declarations

### ISSUE THREAD

**Issue by alany411** [mkosir/react-parallax-tilt#47]
### Description

`Could not find a declaration file for module 'react-parallax-tilt'. 'C:/Users/alany411/Documents/GitHub/react-parallax-tilt-bug/node_modules/react-parallax-tilt/dist/index.umd.js' `

I checked out the package in the node_modules folder and noticed that the types were in a nested folder named `dist`, but in the package.json, it was `"types": "./dist/types/index.d.ts",`

![node_modules folder](https://user-images.githubusercontent.com/20555214/167145784-229c57c5-2fc5-4030-983a-05a9e08d4f30.png)

![package.json](https://user-images.githubusercontent.com/20555214/167147569-bddf06b2-0309-43a8-a2a7-fbff7f9bd301.png)

You can also browse the files through RunKit and see the same:

![runkit](https://user-images.githubusercontent.com/20555214/167174418-baec4bff-bffa-4dcc-a285-cb50cc4e46e0.png)

### Link to Reproduction

Fresh repo:
https://github.com/alany411/react-parallax-tilt-bug

RunKit:
https://npm.runkit.com/react-parallax-tilt

### Steps to reproduce

1. Create new TypeScript project
2. Install react-parallax-tilt
3. Import Tilt from react-parallax-tilt

### Expected behavior

Types to be declared.

### React Parallax Tilt Version

1.7.16

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by mkosir** [comment]
Hey @alany411, thx for the concise bug report 👍 
Type declarations should now be fixed and accessible in newest version `v1.7.17`

**Comment by alany411** [comment]
Thanks @mkosir 💯 
They are indeed working.
