### ISSUE TITLE
How do I make initial position is tilted to signal affordance?

### ISSUE THREAD

**Issue by ajmalafif** [mkosir/react-parallax-tilt#5]
Hi, 

Thanks so much for this package! I am trying to figure out how do I have an initial position tilted to provide affordance to the user? I had a look at Storybook but can't seem to figure it out.

Here's the context of where I want the image to be tilted: https://ajmalafif.com/projects/

**Comment by ajmalafif** [comment]
WOW that was fast from request to implementation! Thank you so much!

**Comment by mkosir** [comment]
Hi @ajmalafif, thanks for the feedback, I'm glad you like the package!
I implemented the proposed feature in newest version `1.3.39`, can you check if [this](https://mkosir.github.io/react-parallax-tilt/?path=/story/react-parallax-tilt--initial-tilt) is what you had in mind?

**Comment by ajmalafif** [comment]
Hi @mkosir, yes exactly this!
