### ISSUE TITLE
Unable to use on node v17/v18

### ISSUE THREAD

**Issue by Crockery** [mkosir/react-parallax-tilt#53]
### Description

Installing this library on node versions greater than 16 produces the following error:

`The engine "node" is incompatible with this module. Expected version "16.x".`

Id love to integrate this library in my app, but this is preventing that.

### Link to Reproduction

n/a

### Expected behavior

Install

### React Parallax Tilt Version

1.7.58

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by mkosir** [comment]
Hey @Crockery 👋 
thx for reporting it, should be fixed in the latest version `1.7.59`, can you try it out and let me know.

**Comment by Crockery** [comment]
Cheers @mkosir!
