### ISSUE TITLE
Uncaught runtime errors

### ISSUE THREAD

**Issue by wkylin** [mkosir/react-parallax-tilt#69]
### Description

Cannot read properties of null (reading 'style')
TypeError: Cannot read properties of null (reading 'style')

### Link to Reproduction - Please provide demo in online code editor [CodeSandbox](https://codesandbox.io/) or similar. - Issues without a reproduction link are likely to stall.

no

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

click

### Code snippets

```jsx
<Tilt reset={false}>
  <MyComponent />
</Tilt>
```

### React Parallax Tilt Version

1.7.163

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by mkosir** [comment]
Hey @wkylin, can you add a bit more details with reproduction example. Thanks.

**Comment by mkosir** [comment]
Closing this issue since inactivity, feel free to reopen it!
