### ISSUE TITLE
Tilt causes crash in Next.js

### ISSUE THREAD

**Issue by aramshiva** [mkosir/react-parallax-tilt#72]
### Description

In Next.js any use of tilt causes an error (seen below):
TypeError: Cannot read properties of undefined (reading 'PureComponent')
    at e (file:///vercel/path0/node_modules/react-parallax-tilt/dist/index.js:1:4112)
    at file:///vercel/path0/node_modules/react-parallax-tilt/dist/index.js:1:10860
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
> Build error occurred
Error: Failed to collect page data for /
    at /vercel/path0/node_modules/next/dist/build/utils.js:1220:15 {
  type: 'Error'

### Link to Reproduction - Please provide demo in online code editor [CodeSandbox](https://codesandbox.io/) or similar. - Issues without a reproduction link are likely to stall.

N/A

### Steps to reproduce

1. Make a next.js project
2. Import react parallax tilt
3. Run `npx next build`
4. Get error

### Expected behavior

ESLint to pass

### React Parallax Tilt Version

1.7.185

**Comment by aramshiva** [comment]
never mind, it was fixed in the latest version, sorry about that!

**Comment by mkosir** [comment]
Thanks for letting me know and closing the issue 👍, just wanted to ask if latest library version works for you.
Went through CJS/ESM module hell to get this package working 🙃
![1_aS0FLuN38Zpps3TSONdcuA](https://github.com/mkosir/react-parallax-tilt/assets/3073826/e87ff97f-6051-4cf8-a8d8-5e5a71ad12e3)
