### ISSUE TITLE
Scroll issues on mobile

### ISSUE THREAD

**Issue by SilasNiewierra** [mkosir/react-parallax-tilt#83]
### Description

Everything works as expected. However on mobile the scroll behavior messes up.
When I click on the component to tilt it, it tilts (as expected) but moving the mouse/finger also moves the entire page.
Is there any way to stop scroll events when clicking the <Tilt> component?

I attached a video so showcase the issue.

Also here is the implementation code:
```jsx
<Tilt
 className="h-full w-full overflow-hidden rounded-xl"
 glareEnable={true}
 glareMaxOpacity={0.2}
 glareColor="white"
 glarePosition="all"
 glareBorderRadius="0px"
>
   <div className="flex h-full w-full items-center justify-center bg-red-500"></div>
</Tilt>
```

https://github.com/user-attachments/assets/7fd55eaa-47ab-442c-9cc5-9b2a78c486e8

### Link to Reproduction - Please provide demo in online code editor [CodeSandbox](https://codesandbox.io/) or similar. - Issues without a reproduction link are likely to stall.

https://www.google.com

### Steps to reproduce

1. Create a div with a fixed height / width
2. Put Tilt component inside
3. Put colored div inside the Tilt component
4. Enable dev tools and change screen size to mobile
5. Click on the Tilt component and move mouse around to enable tilt effect
6. See the issue (scrolling around the page when mouse is down)

### Expected behavior

The tilt should work like it does, but the page shouldn't scroll around it.

### Code snippets

```jsx
   <div
      className={`flip-card-container aspect-[1/1.4] w-[200px] cursor-pointer lg:w-[300px] ${className}`}
      onClick={() => handleFlip()}
    >
      <div className={`flip-card ${isFlipped ? "flipped" : ""}`}>
        <div className="flip-card-inner">
          <div
            className="flip-card-front"
          >
            <Tilt
              className="h-full w-full overflow-hidden rounded-xl"
              glareEnable={true}
              glareMaxOpacity={0.2}
              glareColor="white"
              glarePosition="all"
              glareBorderRadius="0px"
            >
              {frontCard}
            </Tilt>
          </div>
          <div className="flip-card-back">
            <Tilt
              className="h-full w-full overflow-hidden rounded-xl"
              glareEnable={true}
              glareMaxOpacity={0.2}
              glareColor="white"
              glarePosition="all"
              glareBorderRadius="0px"
            >
              {backCard}
            </Tilt>
          </div>
        </div>
      </div>
    </div>
```

### React Parallax Tilt Version

1.7.252

### Browser

Google Chrome V 130.0.6723.92

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I do not have a CodeSandbox link or account, which is why I provided a random google link instead (so I can create this ticket). If a CodeSandbox example is absolutely necessary, I can create one to demonstrate the issue. However, I believe the problem has been clearly described and can be reproduced in just a couple of minutes.

**Comment by SilasNiewierra** [comment]
Hi @mkosir , thanks for the reply.
Unfortunately the "event" is only a string "touchstart".
I would need the full event to stop propagating the scrolling behaviour upwards.
Is there a way to get the full "onEnter" event instead of just the string?

**Comment by mkosir** [comment]
Hey @SilasNiewierra, you can try the newest released version, which includes full event in callback props.

**Comment by SilasNiewierra** [comment]
Thanks @mkosir , I found a way to solve it:
```typescript
useEffect(() => {
		const preventScroll = (e) => {
			if (e.type === 'touchmove' || e.type === 'wheel') {
				e.preventDefault()
			}
		}

		const card = document.getElementById(containerId)
		if (card) {
			card.addEventListener('touchstart', preventScroll, {passive: false})
			card.addEventListener('touchmove', preventScroll, {passive: false})
			card.addEventListener('wheel', preventScroll, {passive: false})

			return () => {
				card.removeEventListener('touchstart', preventScroll)
				card.removeEventListener('touchmove', preventScroll)
				card.removeEventListener('wheel', preventScroll)
			}
		}
	}, [])
```

**Comment by mkosir** [comment]
Awesome stuff, thanks for sharing the feedback!
